'use client';

import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Ban, EyeOff, PauseCircle, Trash2 } from 'lucide-react';
import { apiClient, extractApiErrorMessage } from '@/lib/api-client';
import type { ApiResponse } from '@/types/api';

type Action = 'publish' | 'unpublish' | 'block' | 'suspend' | 'delete';
interface Book { id: number; title: string; cover: string; isPublished: boolean; isBlocked: boolean; suspendedAt: string | null; author: { name: string | null; email: string }; _count: { chapters: number } }
const labels: Record<Action, string> = { publish: 'Publier', unpublish: 'Dépublier', block: 'Bloquer', suspend: 'Suspendre', delete: 'Supprimer' };

export function AdminCatalogueSection() {
  const queryClient = useQueryClient();
  const [confirmation, setConfirmation] = useState<{ book: Book; action: Action } | null>(null);
  const books = useQuery({ queryKey: ['admin', 'catalogue'], queryFn: async () => { const { data } = await apiClient.get<ApiResponse<Book[]>>('/books/administration/catalogue'); if (!data.success) throw new Error(data.message); return data.data; } });
  const moderate = useMutation({ mutationFn: async ({ id, action }: { id: number; action: Action }) => { const { data } = await apiClient.patch<ApiResponse<unknown>>(`/books/${id}/moderation`, { action, confirmationPhrase: 'CONFIRMER' }); if (!data.success) throw new Error(data.message); }, onSuccess: () => { setConfirmation(null); queryClient.invalidateQueries({ queryKey: ['admin', 'catalogue'] }); } });
  if (books.isLoading) return <div className="h-80 animate-pulse rounded-3xl bg-black/[0.04] dark:bg-white/[0.06]" />;
  if (books.isError || !books.data) return <p className="rounded-2xl bg-rose-400/10 p-4 text-sm text-rose-600">{extractApiErrorMessage(books.error, 'Impossible de charger le catalogue.')}</p>;
  return <section className="rounded-[1.75rem] border border-black/8 bg-black/[0.02] p-5 sm:p-6 dark:border-white/8 dark:bg-white/[0.035]"><h2 className="text-xl font-bold">Gestion du catalogue</h2><p className="mt-1 text-sm text-black/45 dark:text-white/45">{books.data.length} livres · chaque opération exige une confirmation.</p>{moderate.isError && <p className="mt-4 text-sm text-rose-600">{extractApiErrorMessage(moderate.error, 'Action impossible.')}</p>}<div className="mt-5 overflow-x-auto rounded-2xl border border-black/8 dark:border-white/8"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-black/[0.035] text-xs text-black/45 dark:bg-white/[0.05] dark:text-white/45"><tr><th className="p-3 font-medium">Livre</th><th className="p-3 font-medium">Auteur</th><th className="p-3 font-medium">Chapitres</th><th className="p-3 font-medium">Statut</th><th className="p-3 font-medium">Actions</th></tr></thead><tbody>{books.data.map((book) => <tr key={book.id} className="border-t border-black/6 dark:border-white/8"><td className="p-3"><div className="flex items-center gap-3"><div className="size-12 shrink-0 rounded-lg bg-cover bg-center bg-black/10" style={{ backgroundImage: `url("${book.cover}")` }}/><span className="max-w-52 truncate font-medium">{book.title}</span></div></td><td className="p-3 text-black/55 dark:text-white/55">{book.author.name ?? book.author.email}</td><td className="p-3">{book._count.chapters}</td><td className="p-3"><Status book={book}/></td><td className="p-3"><div className="flex flex-wrap gap-1.5">{book.isPublished ? <Action icon={EyeOff} label="Dépublier" onClick={() => setConfirmation({ book, action: 'unpublish' })}/> : <Action icon={EyeOff} label="Publier" onClick={() => setConfirmation({ book, action: 'publish' })}/>}<Action icon={Ban} label="Bloquer" onClick={() => setConfirmation({ book, action: 'block' })}/><Action icon={PauseCircle} label="Suspendre" onClick={() => setConfirmation({ book, action: 'suspend' })}/><Action icon={Trash2} label="Supprimer" danger onClick={() => setConfirmation({ book, action: 'delete' })}/></div></td></tr>)}</tbody></table></div>{confirmation && <ConfirmationModal title={confirmation.book.title} action={confirmation.action} loading={moderate.isPending} onClose={() => setConfirmation(null)} onConfirm={() => moderate.mutate({ id: confirmation.book.id, action: confirmation.action })}/>}</section>;
}
function Status({ book }: { book: Book }) { const status = book.isBlocked ? 'Bloqué' : book.suspendedAt ? 'Suspendu' : book.isPublished ? 'Publié' : 'Dépublié'; return <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${status === 'Publié' ? 'bg-emerald-400/15 text-emerald-700 dark:text-emerald-200' : 'bg-rose-400/15 text-rose-600 dark:text-rose-200'}`}>{status}</span>; }
function Action({ icon: Icon, label, danger, onClick }: { icon: typeof Ban; label: string; danger?: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-xs ${danger ? 'border-rose-400/30 text-rose-600' : 'border-black/10 dark:border-white/15'}`}><Icon size={12}/>{label}</button>; }
function ConfirmationModal({ title, action, loading, onClose, onConfirm }: { title: string; action: Action; loading: boolean; onClose: () => void; onConfirm: () => void }) { return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 p-4 backdrop-blur-sm" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !loading) onClose(); }}><section role="dialog" aria-modal="true" className="w-full max-w-sm rounded-3xl bg-background p-6 shadow-2xl"><h3 className="text-lg font-bold">{labels[action]} ce livre ?</h3><p className="mt-2 text-sm leading-6 text-black/55 dark:text-white/55">Vous êtes sur le point de {labels[action].toLowerCase()} « {title} ».</p><div className="mt-6 flex justify-end gap-3"><button type="button" disabled={loading} onClick={onClose} className="rounded-full px-4 py-2 text-sm">Annuler</button><button type="button" disabled={loading} onClick={onConfirm} className="rounded-full bg-rose-500 px-4 py-2 text-sm font-semibold text-white">{loading ? 'Traitement…' : 'Confirmer'}</button></div></section></div>; }
