version: '3.9'

services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - ../.env
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rabipek
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

volumes:
  mysql_data:
