'use client';

import Link from 'next/link';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { MessageCircle, X } from 'lucide-react';
import { apiClient } from '@/lib/api-client';
import { StarRating } from './StarRating';
import type { ApiResponse, Review } from '@/types/api';

export function ReviewsSection({ bookId, initialReviewCount, initialAverageRating }: { bookId: number; initialReviewCount: number; initialAverageRating: number }) {
  const [open, setOpen] = useState(false);
  const reviews = useQuery({ enabled: open, queryKey: ['reviews', bookId], queryFn: async () => { const { data } = await apiClient.get<ApiResponse<Review[]>>(`/comments/book/${bookId}`); if (!data.success) throw new Error(data.message); return data.data; } });
  return <section className="mt-12"><button type="button" onClick={() => setOpen(true)} className="flex items-center gap-2 rounded-full border border-black/10 px-4 py-2.5 text-sm font-semibold hover:border-brand-amber/50 dark:border-white/15"><MessageCircle size={17}/>Avis{initialReviewCount > 0 && <span className="text-black/45 dark:text-white/45">· {initialAverageRating.toFixed(1)} ({initialReviewCount})</span>}</button>{open && <div className="fixed inset-0 z-[90] flex justify-end bg-black/45 backdrop-blur-sm" onMouseDown={(e) => { if (e.target === e.currentTarget) setOpen(false); }}><section role="dialog" aria-modal="true" className="h-full w-full max-w-xl overflow-y-auto bg-background p-5 shadow-2xl sm:p-7"><header className="flex items-start justify-between"><div><h2 className="text-xl font-bold">Avis des lecteurs</h2><p className="mt-1 text-sm text-black/45 dark:text-white/45">La discussion autour de ce livre.</p></div><button onClick={() => setOpen(false)} className="flex size-9 items-center justify-center rounded-full hover:bg-black/5 dark:hover:bg-white/10" aria-label="Fermer"><X size={18}/></button></header><p className="mt-5 text-sm"><Link href="/connexion" className="text-brand-amber underline">Connectez-vous</Link> pour laisser votre avis.</p><div className="mt-6 space-y-5">{reviews.isLoading && <p className="text-sm">Chargement…</p>}{reviews.data?.map((review) => <article key={review.id} className="flex items-start gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-amber-300 to-rose-500 text-sm font-bold text-neutral-950">{(review.user.name ?? 'L').slice(0, 1).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="rounded-[1.45rem] rounded-tl-md bg-black/[0.06] px-4 py-3 dark:bg-white/[0.10]"><div className="flex items-center justify-between gap-3"><strong className="text-sm">{review.user.name ?? 'Lecteur'}</strong><StarRating value={review.rating} size={14}/></div><p className="mt-1.5 text-sm leading-6">{review.message}</p></div>{review.replies[0] && <div className="ml-5 mt-3 flex items-start gap-2"><div className="flex size-7 shrink-0 items-center justify-center rounded-full bg-brand-amber text-[10px] font-black text-black">A</div><div className="rounded-[1.25rem] rounded-tl-md border border-brand-amber/25 bg-brand-amber/10 px-4 py-3"><p className="text-xs font-bold text-brand-amber">Réponse de l’auteur</p><p className="mt-1 text-sm leading-6">{review.replies[0].content}</p></div></div>}</div></article>)}{reviews.data?.length === 0 && <p className="text-sm text-black/45">Aucun avis pour le moment.</p>}</div></section></div>}</section>;
}
